### ISSUE TITLE
Config Summary Sticky Header is All Over the Place 

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/flanksource-ui#1317]
May be move away from sticky header and make body scrollable

https://www.loom.com/share/65baa7a275994c8da40400704a801db1?sid=1a296476-6df4-45ae-b502-7bf8447cc587

**Comment by mainawycliffe** [comment]
@moshloop I think this was fixed when we introduced config summary view as it seems it was a performance issue and can be closed.

**Comment by moshloop** [comment]
I think there is still an issue with the header border color turning
transparent on scroll
